trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: DownloadSecureFile@1
    name: sshCert
    inputs:
      secureFile: "id_devops_to_do"

  - script: yarn
    displayName: "yarn install"

  - script: yarn build
    displayName: "yarn build"

  - script: |
      chmod 400 $CERT_PATH
      scp -i $CERT_PATH -o StrictHostKeyChecking=no -r dist/* luca@159.65.126.196:/var/www/personal-website
    workingDirectory: "$(System.DefaultWorkingDirectory)"
    displayName: "copy files over ssh to digitalocean droplet"
    env:
      CERT_PATH: $(sshCert.secureFilePath)

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)"
      Contents: |
        dist/**
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
