trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: DownloadSecureFile@1
    name: sshCert
    inputs:
      secureFile: "id_devops_to_do"

  - script: yarn
    displayName: "yarn install"

  - script: yarn build
    displayName: "yarn build"

  - task: Bash@3
    inputs:
      targetType: "inline"
      script: "scp -i $CERT_PATH -o StrictHostKeyChecking=no -q -r build/* luca@159.65.126.196:/var/www/personal-website"
      failOnStderr: true
      workingDirectory: "$(System.DefaultWorkingDirectory)"
    env:
      CERT_PATH: $(sshCert.secureFilePath)

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)"
      Contents: |
        build/**
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
      publishLocation: "Container"
