# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: yarn
  displayName: 'yarn install'

- script: yarn build
  displayName: 'yarn build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      build/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh-do-luca'
    sourceFolder: '$(System.ArtifactStagingDirectory)/_lucahost.personal-website/drop/build'
    contents: '**'
    targetFolder: '/var/www/personal-website'
    readyTimeout: '20000'
    failOnEmptySource: true